<?php

// autoload_classmap.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'IntMgr\\IntMgrConn' => $baseDir . '/Src/IntMgrConn.php',
    'IntMgr\\member' => $baseDir . '/Src/member.php',
    'IntMgr\\memberDAO' => $baseDir . '/Src/memberDAO.php',
    'IntMgr\\project' => $baseDir . '/Src/project.php',
    'IntMgr\\projectDAO' => $baseDir . '/Src/projectDAO.php',
    'IntMgr\\projectDAOTest' => $baseDir . '/Tests/projectDAOTest.php',
    'IntMgr\\projectTest' => $baseDir . '/Tests/projectTest.php',
    'Slim\\Environment' => $baseDir . '/api/Slim/Environment.php',
    'Slim\\Exception\\Pass' => $baseDir . '/api/Slim/Exception/Pass.php',
    'Slim\\Exception\\Stop' => $baseDir . '/api/Slim/Exception/Stop.php',
    'Slim\\Http\\Headers' => $baseDir . '/api/Slim/Http/Headers.php',
    'Slim\\Http\\Request' => $baseDir . '/api/Slim/Http/Request.php',
    'Slim\\Http\\Response' => $baseDir . '/api/Slim/Http/Response.php',
    'Slim\\Http\\Util' => $baseDir . '/api/Slim/Http/Util.php',
    'Slim\\Log' => $baseDir . '/api/Slim/Log.php',
    'Slim\\LogWriter' => $baseDir . '/api/Slim/LogWriter.php',
    'Slim\\Middleware' => $baseDir . '/api/Slim/Middleware.php',
    'Slim\\Middleware\\ContentTypes' => $baseDir . '/api/Slim/Middleware/ContentTypes.php',
    'Slim\\Middleware\\Flash' => $baseDir . '/api/Slim/Middleware/Flash.php',
    'Slim\\Middleware\\MethodOverride' => $baseDir . '/api/Slim/Middleware/MethodOverride.php',
    'Slim\\Middleware\\PrettyExceptions' => $baseDir . '/api/Slim/Middleware/PrettyExceptions.php',
    'Slim\\Middleware\\SessionCookie' => $baseDir . '/api/Slim/Middleware/SessionCookie.php',
    'Slim\\Route' => $baseDir . '/api/Slim/Route.php',
    'Slim\\Router' => $baseDir . '/api/Slim/Router.php',
    'Slim\\Slim' => $baseDir . '/api/Slim/Slim.php',
    'Slim\\View' => $baseDir . '/api/Slim/View.php',
    'db\\PDOConnection' => $baseDir . '/db/PDOConnection.php',
);
